import { CalendarDateTime } from "@internationalized/date";

export type Semester = `${number}/${string}`;

export interface Class {
  classId: number, // map to class_id
  courseId: string;
  courseName: string;
  imageUrl?: string;
}

export interface TeachingClass extends Class {
  sections: number[]; // should be string, not exist
}

export interface Student {
  studentId: string;
  name: string;
  // email: string;
  section: number;
  group: string;
  imageUrl?: string;
  withdrawed: boolean;
  // TODO: think about this
  score: number;
  maxScore: number;
}

export interface Instructor {
  name: string;
  imageUrl?: string;
  email: string;
}

export interface ClassParticipants {
  instructors: Instructor[],
  teachingAssistants: TeachingAssistant[],
  students: Student[],
}

export interface TeachingAssistant {
  name: string;
  email: string;
  imageUrl?: string;
  leader: boolean;
}

export interface LabNotification {
  courseId: number;
  courseName: string;
  id: number;
  name: string;
  due: Date;
  maxScore: number;
}

export interface Testcase {
  input: string;
  output: string;
}

// TODO: map this to api type
export interface Question {
  id: number;
  number: number; // autogenerated, by index probably
  name: string;
  description: string;
  template: string; // predefine

  maxScore: number;
}

export interface StudentQuestion extends Question {
  submission?: {
    id: number;
    score: number;
    submittedAt: CalendarDateTime;
  };
}

export interface InstructorQuestion extends Question {
  answer: string;

  testCode: string; // wtf is the differences
  secretTestCode: string;

  testcases: Testcase[];
  secretTestCases: Testcase[];
}

export type SupportedLanguage = {
  id: number; // e.g. 1, 2, 3
  name: string; // e.g. "C++", "Python 3"
};

// ===========

export interface InstructorsAndTAs {
  instructors: Instructor[],
  teachingAssistant: TeachingAssistant[];
}

export interface ParticipatingClasses {
  studying: Class[];
  assisting: Class[];
}

export interface CreateStudentPayload {
  email: string,
  section: number,
  group?: string;
}

export interface UpdateStudentPayload {
  section?: number,
  group?: string,
  withdrawed?: boolean;
}

export interface CreateClassPayload {
  courseId: string;
  name: string;
  semester: Semester;
  image?: File;
  /**
   * Student csv file
   */
  students?: File;
}

export type UpdateClassPayload = Partial<CreateClassPayload>;


export type AssignmentStatus = "new" | "partially-completed" | "completed" | "lated" | "due-soon";

export type NearDueAssignment = {
  id: number;
  name: string;
  maxScore: number;
  due: CalendarDateTime; // RFC3339: 1996-12-19T16:39:57+07:00
  courseName: string;
  courseId: string;
};

export interface Assignment {
  id: number;
  number: number;
  name: string;
  publish: CalendarDateTime;
  due: CalendarDateTime;
}

export interface AssignmentDetails {
  questionIds: number[];
  additionalFileIds: number[];
  languages: SupportedLanguage[];
  examMode: boolean;
  closeOnDue: boolean;
  assignedGroupIds: string[];
}

export interface InstructorAssignmentDetailsFields {
  examPin: string;
  showScoreOnLock: boolean;
  testCode: string;
  secretTestCode: string;
}

// TODO: omit a lot more
export interface StudentAssignment extends Assignment {
  score: number;
  status: AssignmentStatus;
}

export interface StudentAssignmentDetails extends StudentAssignment, AssignmentDetails {
  questions: StudentQuestion[];
}

export type InstructorAssignment = Assignment;

export interface InstructorAssignmentDetails extends InstructorAssignment, AssignmentDetails, InstructorAssignmentDetailsFields {
  questions: InstructorQuestion[];
}


export interface QuestionSubmissionPayload {
  questionId: number;
  languageId: number;
  code: string;
}

export type CreateAssignmentPayload = Omit<InstructorAssignment, "id"> & {
  // Required fields for creation
  examPin: string;
  showScoreOnLock: boolean;
  testCode: string;
  secretTestCode: string;
  languageIds: number[];
  examMode: boolean;
  closeOnDue: boolean;
  assignedGroupIds: string[];
  questions: Omit<InstructorQuestion, "id">[];
};

export type UpdateAssignmentPayload = Partial<CreateAssignmentPayload>;


export interface CodePage { // ?????
  pageName: string;
  content: string;
}

export interface SubmissionResult {
  public: PublicTestcaseResult[];
  secret: SecretTestcaseResult[];
}

export interface PublicTestcaseResult {
  input: string; // TODO: request output if ui need it
  expectedOutput: string | null; // ????
  message: string;
  status: "pass" | "fail";
}

export type SecretTestcaseResult = Omit<PublicTestcaseResult, "input" | "expectedOutput">;

export interface CodeSubmission {
  submissionId: number;
  code: CodePage[];
  language: SupportedLanguage;
}

export interface APIClient {
  students: {
    addToClass: (classId: number, payload: CreateStudentPayload) => Promise<void>,
    listByClass: (classId: number) => Promise<Student[]>,
    removeFromClass: (classId: number, studentId: string) => Promise<void>,
    update: (classId: number, studentId: string, data: UpdateStudentPayload) => Promise<void>,
    updateMany: (classId: number, studentIds: string[], data: UpdateStudentPayload) => Promise<void>,
  },
  classes: {
    getById: (classId: number) => Promise<Class>,
    listParticipatingBySemester: (semester: Semester) => Promise<ParticipatingClasses>,
    create: (payload: CreateClassPayload) => Promise<void>, // should it tho
    update: (classId: number, payload: UpdateClassPayload) => Promise<void>,
    // จารย์พลอยไม่เอา
    // delete: (classId: number) => Promise<void>,
  },
  sections: {
    getByClass: (classId: number) => Promise<number[]>;
  };
  semesters: {
    list: () => Promise<Semester[]>,
  },
  instructorsAndTAs: {
    listByClass: (classId: number) => Promise<InstructorsAndTAs>,
    addToClass: (classId: number, email: string) => Promise<void>,
    removeFromClass: (classId: number, email: string) => Promise<void>,
  },

  assignments: {
    listNearDue: () => Promise<NearDueAssignment[]>;
    listByClass: (classId: number) => Promise<StudentAssignment[]>;
    listByClassI: (classId: number) => Promise<InstructorAssignment[]>;

    getById: (labId: number) => Promise<StudentAssignmentDetails>;
    getByIdI: (labId: number) => Promise<InstructorAssignmentDetails>;

    create: (classId: number, payload: CreateAssignmentPayload) => Promise<void>;
    update: (labId: number, payload: UpdateAssignmentPayload) => Promise<void>;

    attachFile: (assignmentId: number, file: File) => Promise<void>;
    removeFile: (fileId: number) => Promise<void>;
    downloadFile: (fileId: number) => Promise<Blob>;
  };
  questions: {
    getById: (questionId: number) => Promise<StudentQuestion>;
    getByIdI: (questionId: number) => Promise<InstructorQuestion>;

    submit: (questionId: number, languageId: number, codes: CodePage[]) => Promise<{ submissionId: number; }>;
    getSubmission: (questionId: number) => Promise<CodeSubmission>;
    requestGrade: (submissionId: number) => Promise<void>;
    getSubmissionResult: (submissionId: number) => Promise<SubmissionResult>;
  };
  supportedLanguages: {
    list: () => Promise<SupportedLanguage[]>;
  };
  groups: {
    listByClassId: (classId: number) => Promise<string[]>;
  };
  examPin: {
    getByAssignmentId: (assignmentId: number) => Promise<string>;
  };
  testCode: { // TODO: rename this
    getById: (testCodeId: number) => Promise<string>;
  };
  testcase: { // TODO: rename this
    listByQuestionId: (testCodeId: number) => Promise<{ public: Testcase[], secret: Testcase[]; }>;
  };
};
